import csv
import io
from datetime import datetime

import streamlit as st

from app.services import (
    TIER_BADGE_CLASS,
    TIER_SCORE_CLASS,
    explain_order,
    get_risk_tier,
    required_actions,
)
from app.state import load_model

st.subheader("Evidence vault")
st.caption("Tamper-proof delivery records")

orders = st.session_state.orders
delivered = sorted(
    (o for o in orders if o["delivered"]),
    key=lambda o: o["delivered_at"],
    reverse=True,
)

total_deliveries = len(delivered)
otp_verified_count = sum(1 for o in delivered if o["otp_verified"])
signatures_required_count = sum(
    1 for o in delivered if "esign" in required_actions(get_risk_tier(o["risk_score"]))
)

st.markdown(
    f"""
    <div class="vault-stat-row">
        <div class="vault-stat-card">
            <div class="vault-stat-value">{total_deliveries}</div>
            <div class="vault-stat-label">Total deliveries</div>
        </div>
        <div class="vault-stat-card">
            <div class="vault-stat-value">{otp_verified_count}</div>
            <div class="vault-stat-label">OTP verified</div>
        </div>
        <div class="vault-stat-card">
            <div class="vault-stat-value">{signatures_required_count}</div>
            <div class="vault-stat-label">Signatures required</div>
        </div>
        <div class="vault-stat-card">
            <div class="vault-stat-value">{total_deliveries}</div>
            <div class="vault-stat-label">Zero disputes</div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

if not delivered:
    st.info("No delivered orders yet. Confirm a delivery to see it here.", icon=":material/info:")
    st.stop()


def format_timestamp(iso_string):
    try:
        return datetime.fromisoformat(iso_string).strftime("%b %d, %Y %H:%M")
    except (TypeError, ValueError):
        return iso_string or "—"


def build_proof_text(order, tier, top_reasons):
    lines = [
        "AURANTIS — DELIVERY PROOF",
        "=" * 40,
        f"Order ID: #{order['order_id']}",
        f"Customer: {order['customer_name']}",
        f"Product: {order['product_name']}",
        f"Amount: Rs. {order['amount']:,.2f}",
        f"Risk score: {order['risk_score']:.3f} ({tier.upper()})",
        "Top risk reasons:",
        *[f"  - {reason}" for reason in top_reasons],
        "",
    ]
    if order.get("otp_provider") == "verify":
        lines.append(f"OTP verified: Yes, at {order['otp_verified_at']} (via Twilio Verify)")
    else:
        lines.append(f"OTP verified: Yes, at {order['otp_verified_at']} (code {order['otp_code']})")
    if "esign" in required_actions(tier):
        lines.append(
            f"E-signature: Signed by {order['esign_signer']} at {order['esign_signed_at']}"
        )
    else:
        lines.append("E-signature: Not required for this risk tier")
    lines.append(f"Delivered at: {order['delivered_at']}")
    lines.append("")
    lines.append("Generated by Aurantis Return-Risk Intelligence")
    return "\n".join(lines)


model = load_model()

with st.container(border=True, key="evidence_vault_card"):
    st.markdown("<h3>Delivered orders</h3>", unsafe_allow_html=True)

    header_cols = st.columns([1.0, 0.8, 0.8, 0.9, 1.1, 1.2, 1.3])
    headers = ["Order ID", "Amount", "Risk score", "OTP verified", "Signature required", "Timestamp", "Proof"]
    for col, label in zip(header_cols, headers):
        col.markdown(f'<div class="table-header">{label}</div>', unsafe_allow_html=True)

    for order in delivered:
        tier = get_risk_tier(order["risk_score"])
        badge_class = TIER_BADGE_CLASS[tier]
        score_class = TIER_SCORE_CLASS[tier]
        needs_esign = "esign" in required_actions(tier)

        row = st.columns([1.0, 0.8, 0.8, 0.9, 1.1, 1.2, 1.3], vertical_alignment="center")
        row[0].markdown(
            f'<div class="order-id">#{order["order_id"]}</div>'
            f'<div class="order-meta">{order["customer_name"]}</div>',
            unsafe_allow_html=True,
        )
        row[1].markdown(f'<div class="order-meta">₹{order["amount"]:,.2f}</div>', unsafe_allow_html=True)
        row[2].markdown(
            f'<span class="badge {badge_class}"><span class="risk-score-text {score_class}">{order["risk_score"]:.3f}</span></span>',
            unsafe_allow_html=True,
        )
        row[3].markdown(
            '<span class="badge badge-green">✓ Verified</span>',
            unsafe_allow_html=True,
        )
        if needs_esign:
            row[4].markdown(
                f'<span class="badge badge-green">✓ Signed</span>'
                f'<div class="order-meta">{order["esign_signer"]}</div>',
                unsafe_allow_html=True,
            )
        else:
            row[4].markdown('<span class="badge badge-grey">Not required</span>', unsafe_allow_html=True)
        row[5].markdown(
            f'<div class="order-meta">{format_timestamp(order["delivered_at"])}</div>',
            unsafe_allow_html=True,
        )

        top_reasons = explain_order(model, order)["top_reasons"]
        proof_text = build_proof_text(order, tier, top_reasons)
        row[6].download_button(
            "Download",
            data=proof_text,
            file_name=f"aurantis_order_{order['order_id']}_proof.txt",
            mime="text/plain",
            key=f"proof_{order['order_id']}",
            icon=":material/download:",
        )

report_buffer = io.StringIO()
writer = csv.writer(report_buffer)
writer.writerow(
    ["Order ID", "Amount", "Risk Score", "Risk Level", "OTP Verified", "Signature Required", "Delivered At"]
)
for order in delivered:
    tier = get_risk_tier(order["risk_score"])
    needs_esign = "esign" in required_actions(tier)
    writer.writerow(
        [
            order["order_id"],
            f"{order['amount']:.2f}",
            f"{order['risk_score']:.3f}",
            tier.upper(),
            "Yes" if order["otp_verified"] else "No",
            "Yes" if needs_esign else "No",
            order["delivered_at"],
        ]
    )

st.download_button(
    "Download evidence report",
    data=report_buffer.getvalue(),
    file_name="aurantis_evidence_report.csv",
    mime="text/csv",
    icon=":material/summarize:",
)
